"""updated users table

Revision ID: c0fed31b4104
Revises: 163489b6295b
Create Date: 2026-04-29 11:52:33.582598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'c0fed31b4104'
down_revision: Union[str, Sequence[str], None] = '163489b6295b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("""
    ALTER TABLE users
    ALTER COLUMN is_active TYPE BOOLEAN
    USING(
        CASE
            WHEN is_active IN ('tru', 't', 'yes', 'y') THEN TRUE
            ELSE FALSE
        END
    )
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("""
    ALTER TABLE users
    ALTER COLUMN is_active TYPE VARCHAR(2)
    USING(
        CASE
            WHEN is_active = TRUE THEN '1'
            ELSE '0'
        END
    )
    """))
    # ### end Alembic commands ###
