"""initial database migration

Revision ID: f289bf9daa1d
Revises: 
Create Date: 2026-04-22 20:20:03.513030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f289bf9daa1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=False),
    sa.Column('gender_probability', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.VARCHAR(), nullable=False),
    sa.Column('country_id', sa.VARCHAR(length=2), nullable=False),
    sa.Column('country_name', sa.VARCHAR(), nullable=False),
    sa.Column('country_probability', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='profiles_id_pk'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_profiles_age', 'profiles', ['age'], unique=False)
    op.create_index('idx_profiles_composite_1', 'profiles', ['country_id', 'age', 'gender'], unique=False)
    op.create_index('idx_profiles_composite_2', 'profiles', ['country_id', 'age', 'age_group'], unique=False)
    op.create_index('idx_profiles_country_id', 'profiles', ['country_id'], unique=False)
    op.create_index('idx_profiles_created_at', 'profiles', ['created_at'], unique=False)
    op.create_index('idx_profiles_gender_probability', 'profiles', ['gender_probability'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_profiles_gender_probability', table_name='profiles')
    op.drop_index('idx_profiles_created_at', table_name='profiles')
    op.drop_index('idx_profiles_country_id', table_name='profiles')
    op.drop_index('idx_profiles_composite_2', table_name='profiles')
    op.drop_index('idx_profiles_composite_1', table_name='profiles')
    op.drop_index('idx_profiles_age', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
